apiVersion: sro.openshift.io/v1alpha1
kind: SpecialResource
metadata:
  name: REPLACE_SPECIALRESOURCE
  namespace: REPLACE_NAMESPACE
spec:
  # Add fields here
  size: 3


# CUDA10    410.129    410.129-diagnostic
# CUDA10.1  418.87     418.87.01
# CUDA10.2  440.33.01  440.33.01


